# Generated by Django 2.2.4 on 2019-09-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
