# Generated by Django 2.2.4 on 2019-09-09 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(default=0, max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('industrial', 'Industrial'), ('comercial', 'Comercial')], max_length=30)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('componente', models.CharField(max_length=200)),
                ('concentracion', models.CharField(max_length=50)),
                ('sanitario', models.CharField(max_length=200)),
                ('fecha_expiracion', models.DateField()),
                ('fecha_produccion', models.DateField()),
                ('descripcion', models.TextField(max_length=400)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock', models.PositiveSmallIntegerField()),
                ('iva', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Presentacion')),
            ],
        ),
    ]
